version: '3.7'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=grygoryz
      - POSTGRES_PASSWORD=123123
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  redis:
