version: '3.7'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=grygoryz
      - POSTGRES_PASSWORD=123123
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      
  server:
    build:
      context: ./server
    command: sh -c 'npm run migrate && npm run start:dev'
    environment:
      - NODE_ENV=production
      - POSTGRES_DB=blog
      - POSTGRES_USER=grygoryz
      - POSTGRES_PASSWORD=123123
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - PORT=3000
    ports:
      - "4000:3000"
    depends_on:
      - postgres
        
  client:
    build:
      context: ./client
    ports:
      - "3000:80"

volumes:
  postgres:
